# Generated by Django 6.0.7 on 2026-07-31 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolio_create_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeline_date', models.CharField(blank=True, default='', max_length=256)),
                ('timeline_org', models.CharField(blank=True, default='', max_length=256)),
                ('timeline_title', models.CharField(blank=True, default='', max_length=256)),
                ('timeline_desc', models.TextField(blank=True, null=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='journeys', to='portfolio.portfolio')),
            ],
        ),
    ]
