# Generated by Django 6.0.7 on 2026-07-31 13:13

import django.db.models.deletion
import django.db.models.query
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_lifejourney'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifejourney',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lifejourney',
            name='portfolio',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, on_delete=django.db.models.deletion.DO_NOTHING, related_name='journeys', to='portfolio.portfolio'),
        ),
    ]
