# Generated by Django 6.0.7 on 2026-08-03 06:16

import django.db.models.deletion
import django.db.models.query
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_lifejourney_order_alter_lifejourney_portfolio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lifejourney',
            options={'ordering': ['-order']},
        ),
        migrations.AddField(
            model_name='portfolio',
            name='rout_url',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='lifejourney',
            name='portfolio',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, on_delete=django.db.models.deletion.DO_NOTHING, related_name='journeys', to='portfolio.portfolio'),
        ),
    ]
