# Generated by Django 6.0.7 on 2026-08-03 06:31

import django.db.models.deletion
import django.db.models.query
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_portfolio_github_portfolio_leetcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='user_full_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='user_name_logo',
            field=models.CharField(default='Xenon', max_length=20),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='user_short_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='lifejourney',
            name='portfolio',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, on_delete=django.db.models.deletion.DO_NOTHING, related_name='journeys', to='portfolio.portfolio'),
        ),
    ]
