# Generated by Django 6.0.7 on 2026-08-03 06:45

import django.db.models.deletion
import django.db.models.query
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_portfolio_user_full_name_portfolio_user_name_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='user_name_logo',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='logo_text_mark',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='lifejourney',
            name='portfolio',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, on_delete=django.db.models.deletion.DO_NOTHING, related_name='journeys', to='portfolio.portfolio'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='github',
            field=models.URLField(blank=True, default='#', null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='leetcode',
            field=models.URLField(blank=True, default='#', null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='linked_in',
            field=models.URLField(blank=True, default='#', null=True),
        ),
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_text_mark', models.CharField(blank=True, default='', max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=256)),
                ('organization', models.CharField(blank=True, default='', max_length=256)),
                ('issue_date', models.CharField(blank=True, default='', max_length=50)),
                ('verify_link', models.URLField(blank=True, default='#', null=True)),
                ('portfolio', models.ForeignKey(default=django.db.models.query.QuerySet.first, on_delete=django.db.models.deletion.DO_NOTHING, related_name='certificates', to='portfolio.portfolio')),
            ],
        ),
    ]
