# Generated by Django 6.0.7 on 2026-08-03 06:50

import django.db.models.deletion
import django.db.models.query
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_lifejourney_portfolio_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='portfolio',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, on_delete=django.db.models.deletion.DO_NOTHING, related_name='certificates', to='portfolio.portfolio'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='verify_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lifejourney',
            name='portfolio',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, on_delete=django.db.models.deletion.DO_NOTHING, related_name='journeys', to='portfolio.portfolio'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='leetcode',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='linked_in',
            field=models.URLField(blank=True, null=True),
        ),
    ]
