# Generated by Django 6.0.7 on 2026-08-03 07:02

import django.db.models.deletion
import django.db.models.query
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_certificate_portfolio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-order']},
        ),
        migrations.AddField(
            model_name='certificate',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='portfolio',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, on_delete=django.db.models.deletion.DO_NOTHING, related_name='certificates', to='portfolio.portfolio'),
        ),
        migrations.AlterField(
            model_name='lifejourney',
            name='portfolio',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, on_delete=django.db.models.deletion.DO_NOTHING, related_name='journeys', to='portfolio.portfolio'),
        ),
    ]
