# Generated by Django 6.0.7 on 2026-08-03 11:21

import django.db.models.deletion
import django.db.models.query
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_certificate_options_certificate_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='portfolio',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='portfolio.portfolio'),
        ),
        migrations.AlterField(
            model_name='lifejourney',
            name='portfolio',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journeys', to='portfolio.portfolio'),
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('card_icon_text', models.CharField(blank=True, default='', max_length=20)),
                ('category_name', models.CharField(blank=True, default='', max_length=50)),
                ('portfolio', models.ForeignKey(default=django.db.models.query.QuerySet.first, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_category', to='portfolio.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('category', models.ForeignKey(default=django.db.models.query.QuerySet.first, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_category', to='portfolio.skillcategory')),
            ],
        ),
    ]
