# Generated by Django 6.0.7 on 2026-08-03 13:32

import django.db.models.deletion
import django.db.models.query
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_project_screenshot_alter_certificate_portfolio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='live_demo',
            new_name='live_link',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='portfolio',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='portfolio.portfolio'),
        ),
        migrations.AlterField(
            model_name='lifejourney',
            name='portfolio',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journeys', to='portfolio.portfolio'),
        ),
        migrations.AlterField(
            model_name='project',
            name='portfolio',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='portfolio.portfolio'),
        ),
        migrations.AlterField(
            model_name='project',
            name='screenshot',
            field=models.ImageField(blank=True, help_text='e.g. expected 300x300 resolution', null=True, upload_to='project_shots/'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='portfolio.skillcategory'),
        ),
        migrations.AlterField(
            model_name='skillcategory',
            name='portfolio',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_category', to='portfolio.portfolio'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='project',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='portfolio.project'),
        ),
    ]
