# Generated by Django 6.0.7 on 2026-08-05 08:11

import django.db.models.deletion
import django.db.models.query
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0026_portfolio_job_title_alter_badgetext_portfolio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tag_list',
            field=models.CharField(blank=True, default='', help_text='e.g. tag1, tag2, ', max_length=256),
        ),
        migrations.AlterField(
            model_name='badgetext',
            name='portfolio',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badge_texts', to='portfolio.portfolio'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='portfolio',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='portfolio.portfolio'),
        ),
        migrations.AlterField(
            model_name='lifejourney',
            name='portfolio',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journeys', to='portfolio.portfolio'),
        ),
        migrations.AlterField(
            model_name='project',
            name='portfolio',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='portfolio.portfolio'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='portfolio.skillcategory'),
        ),
        migrations.AlterField(
            model_name='skillcategory',
            name='portfolio',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_category', to='portfolio.portfolio'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='project',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='portfolio.project'),
        ),
        migrations.AlterField(
            model_name='typedtext',
            name='portfolio',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typed_texts', to='portfolio.portfolio'),
        ),
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(blank=True, default='', max_length=256)),
                ('overview', models.TextField(blank=True, null=True)),
                ('features', models.TextField(blank=True, help_text='e.g. feature1\n, feature2\n, ', null=True)),
                ('tags', models.CharField(blank=True, default='', help_text='e.g. tag1, tag2, ', max_length=256)),
                ('learned', models.TextField(blank=True, null=True)),
                ('portfolio', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='portfolio.project')),
            ],
        ),
    ]
